"""The LLM ``Summarizer`` impl behind the 085 seam (task 090, M12).

``LLMSummarizer`` replaces only the prose ``docline`` with a one-sentence Claude summary; the
``signature`` and the 083-derived ``role`` come from the deterministic ``StructuralSummarizer``
(DRY, R7.4 — role refinement is 091, not here). Every generation is memoised in a content-hash
cache, so a committed cache makes runs replay byte-for-byte (R4.2). The ``anthropic`` SDK is
imported lazily by the factory alone, so importing this module — as the test suite does — pulls in
no LLM and touches no network (R4.1: the LLM path never runs in the per-PR gate).
"""

from __future__ import annotations

from typing import Protocol

from code_atlas.onboarding.summary import NodeFacts, StructuralSummarizer, Summary
from onboarding_llm.cache import ContentHashCache, content_key

# Mid tier for per-module summaries per PHASE3 §4 (M12); a top tier is 091's layer pass, not here.
# Override with CA_ONBOARDING_LLM_MODEL. Model ids: claude-api skill, Current Models.
DEFAULT_MODEL = "claude-sonnet-5"

# The system prompt asks for one sentence; the budget leaves room for a model's adaptive thinking
# too (thinking tokens count against it), so a long input can't truncate the answer to empty.
MAX_TOKENS = 2048

# An explicit manual cache-buster; the prompt text and MAX_TOKENS are also folded into the key, so
# an edit to either invalidates cached entries without anyone remembering to bump this.
PROMPT_VERSION = "1"

_SYSTEM = (
    "You summarise one code module for an onboarding guide. Given its path, signature, docblock, "
    "and structural role, reply with a single concise sentence describing what the module does. "
    "Output only that sentence — no preamble, no markdown, no quotes."
)


class _Client(Protocol):
    """The slice of the ``anthropic`` client used here — a test injects a fake (no network)."""

    @property
    def messages(self) -> _Messages: ...


class _Messages(Protocol):
    def create(self, **kwargs: object) -> object: ...


class LLMSummarizer:
    """A ``Summarizer`` (085 seam) whose ``docline`` is generated by Claude, cached by content."""

    def __init__(
        self,
        client: _Client,
        model: str,
        cache: ContentHashCache,
        *,
        prompt_version: str = PROMPT_VERSION,
    ) -> None:
        self._client = client
        self._model = model
        self._cache = cache
        self._prompt_version = prompt_version
        self._structural = StructuralSummarizer()

    def summarize(self, facts: NodeFacts) -> Summary:
        """Structural signature/role verbatim; ``docline`` from the cache, or Claude on a miss."""
        base = self._structural.summarize(facts)
        return Summary(base.key, base.signature, self._docline(facts, base), base.role)

    def _docline(self, facts: NodeFacts, base: Summary) -> str:
        key = content_key(
            base.key, facts.signature, facts.doc, facts.metric.direction, self._model,
            self._prompt_version, _SYSTEM, str(MAX_TOKENS),
        )
        cached = self._cache.get(key)
        if cached and cached.get("docline"):  # a missing/empty entry is a miss, not a KeyError
            return cached["docline"]
        docline = self._generate(facts, base)
        if not docline:  # a refusal or truncation gives nothing — fall back, never cache the blank
            return base.docline
        self._cache.put(key, {"docline": docline, "module": base.key, "model": self._model})
        return docline

    def _generate(self, facts: NodeFacts, base: Summary) -> str:
        # Only params every model and SDK version accept — the model is operator-configurable, so no
        # output_config/thinking knob that a given model or an older `anthropic` could reject.
        message = self._client.messages.create(
            model=self._model,
            max_tokens=MAX_TOKENS,
            system=_SYSTEM,
            messages=[{"role": "user", "content": _prompt(facts, base)}],
        )
        return _first_text(message).strip()


def _prompt(facts: NodeFacts, base: Summary) -> str:
    """The per-module facts, one field per line — deterministic given identical facts."""
    return (
        f"Path: {base.key}\n"
        f"Signature: {facts.signature or '(none)'}\n"
        f"Docblock: {facts.doc or '(none)'}\n"
        f"Structural role: {base.role}"
    )


def _first_text(message: object) -> str:
    """The first text block of an Anthropic message, tolerant of the fake client used in tests."""
    for block in getattr(message, "content", None) or []:
        if getattr(block, "type", None) == "text":
            return getattr(block, "text", "") or ""
    return ""
