#!/usr/bin/env python3
"""Emit the offered `contrib/` artifacts from the surface the server actually serves (task 200).

The recognition map, the tool roster and every adapter suffix are READ from where they already
live and never re-typed beside them (R6.7) — a hand-kept copy is exactly how 036's PHP-only hook
filter rotted. `--write` regenerates; the guards in `tests/` compare the committed bytes to this.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from code_atlas.adapter import ADAPTERS_DIR, shipped_adapters  # noqa: E402
from code_atlas.main import TOOL_NAMES  # noqa: E402
from code_atlas.tools import prompts  # noqa: E402

SKILL_PATH = REPO / "contrib" / "skill" / "SKILL.md"
POKE_SNIPPET_PATH = REPO / "contrib" / "claude-code" / "settings.snippet.json"

# An adapter announces its suffixes in its entry file; the handshake sends this same literal.
# Reading it statically is what lets a guard check coverage without starting a subprocess.
_EXT_DECL = re.compile(r"""extensions['"]?\s*(?::|=>)\s*[\[(]([^\])]*)[\])]""")
_EXT_ITEM = re.compile(r"""['"](\.[A-Za-z0-9_]+)['"]""")


class _PromptRecorder:
    """Stands in for the FastMCP server so `prompts.register` can be read, not imported.

    `which_tool` is a closure inside `register`, and `register` only ever calls
    `server.prompt(name=…)(fn)` — so one method is the whole surface it needs.
    """

    def __init__(self) -> None:
        self.prompts: dict[str, Callable[..., str]] = {}

    def prompt(self, name: str) -> Callable[[Callable[..., str]], Callable[..., str]]:
        def keep(fn: Callable[..., str]) -> Callable[..., str]:
            self.prompts[name] = fn
            return fn

        return keep


def recognition_map() -> list[str]:
    """The `which_tool` map, as its `- question -> tool.` lines, in the order the prompt emits."""
    recorder = _PromptRecorder()
    prompts.register(recorder)  # type: ignore[arg-type]
    body = recorder.prompts[prompts.WHICH_TOOL]()
    return [line for line in body.splitlines() if line.startswith("- ")]


def declared_extensions(adapters_dir: Path | None = None) -> dict[str, tuple[str, ...]]:
    """Each shipped adapter's declared suffixes, read from its own entry file.

    An adapter whose declaration does not parse maps to `()` — so it reads as uncovered and turns
    the coverage guard red, rather than passing quietly.
    """
    root = ADAPTERS_DIR if adapters_dir is None else adapters_dir
    found: dict[str, tuple[str, ...]] = {}
    for name in shipped_adapters(root):
        found[name] = ()
        for path in sorted(p for p in (root / name).iterdir() if p.is_file()):
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            match = _EXT_DECL.search(text)
            if match:
                found[name] = tuple(_EXT_ITEM.findall(match.group(1)))
                break
    return found


def render_skill() -> str:
    """`SKILL.md` — the map plus the roster, and nothing that could disagree with the server."""
    lines = [
        "---",
        "name: code-atlas",
        "description: >-",
        "  Route a question about an unfamiliar codebase to the right code-atlas MCP tool —",
        "  search, read, callers, references, impact, architecture, onboarding. Use when the",
        "  code-atlas server is connected and you are deciding which of its tools answers the",
        "  question in front of you.",
        "---",
        "",
        "# code-atlas — which tool answers which question",
        "",
        f"Generated by `scripts/gen_skill.py` from the {len(TOOL_NAMES)} tools the server",
        "registers and from the `which_tool` recognition map. Do not edit by hand: a drift guard",
        "compares this file to its source, so a hand edit is a red test, not a quiet",
        "disagreement.",
        "",
        "## Recognition map",
        "",
    ]
    lines.extend(recognition_map())
    lines.extend(
        [
            "",
            "Call `get_index_status` first whenever you are unsure the index is current.",
            "",
            "## The served surface",
            "",
        ]
    )
    lines.extend(f"{n}. `{name}`" for n, name in enumerate(TOOL_NAMES, start=1))
    lines.extend(
        [
            "",
            "## What this skill is not",
            "",
            "It carries the map, never a second set of tool descriptions — the descriptions the",
            "client shows you are the ones that route, and a copy here could disagree with them.",
            "It holds no live state either: index freshness, symbol counts and open work are what",
            "the tools are for, and a number frozen into this file would be a wrong answer rather",
            "than a stale one.",
            "",
        ]
    )
    return "\n".join(lines)


def render_poke_snippet() -> str:
    """The Claude Code Edit/Write poke hook, filtered to every shipped adapter's suffixes."""
    suffixes = [suffix for _, group in sorted(declared_extensions().items()) for suffix in group]
    matchers = "|".join(f"Edit(*{s})|Write(*{s})" for s in suffixes)
    snippet: dict[str, Any] = {
        "hooks": {
            "PostToolUse": [
                {
                    "matcher": "Edit|Write",
                    "hooks": [
                        {
                            "type": "command",
                            "command": "code-atlas-poke",
                            "if": matchers,
                            "async": True,
                            "timeout": 60,
                        }
                    ],
                }
            ]
        }
    }
    return json.dumps(snippet, indent=2) + "\n"


GENERATED: dict[Path, Callable[[], str]] = {
    SKILL_PATH: render_skill,
    POKE_SNIPPET_PATH: render_poke_snippet,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="rewrite the generated files in place")
    args = parser.parse_args(argv)
    stale = []
    for path, render in GENERATED.items():
        wanted = render()
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(wanted, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO)}")
        elif not path.is_file() or path.read_text(encoding="utf-8") != wanted:
            stale.append(path.relative_to(REPO).as_posix())
    for name in stale:
        print(f"stale: {name} — run `python scripts/gen_skill.py --write`", file=sys.stderr)
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
