#!/usr/bin/env python3
"""Emit the offered `contrib/` artifacts from the surface the server actually serves (task 200).

The recognition map, the tool roster and every adapter suffix are READ from where they already
live and never re-typed beside them (R6.7) — a hand-kept copy is exactly how 036's PHP-only hook
filter rotted. `--write` regenerates; the guards in `tests/` compare the committed bytes to this.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from collections.abc import Callable
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from code_atlas.adapter import ADAPTERS_DIR, shipped_adapters  # noqa: E402
from code_atlas.main import TOOL_NAMES  # noqa: E402
from code_atlas.tools import prompts  # noqa: E402

SKILL_PATH = REPO / "contrib" / "skill" / "SKILL.md"
CLAUDE_CODE_SNIPPET_PATH = REPO / "contrib" / "claude-code" / "settings.snippet.json"
AGENT_BRIEF_PATH = REPO / "contrib" / "agent-brief.md"
# The name 240 found drifted: the file carries every Claude Code hook, not only the poke.
POKE_SNIPPET_PATH = CLAUDE_CODE_SNIPPET_PATH
# 344: the same hooks, the server and the skill as one Claude Code plugin, plus its marketplace.
PLUGIN_DIR = REPO / "contrib" / "claude-code" / "plugin"
PLUGIN_MANIFEST_PATH = PLUGIN_DIR / ".claude-plugin" / "plugin.json"
PLUGIN_MCP_PATH = PLUGIN_DIR / ".mcp.json"
PLUGIN_HOOKS_PATH = PLUGIN_DIR / "hooks" / "hooks.json"
PLUGIN_SKILL_PATH = PLUGIN_DIR / "skills" / "code-atlas" / "SKILL.md"
MARKETPLACE_PATH = REPO / ".claude-plugin" / "marketplace.json"
REPOSITORY_URL = "https://github.com/cuongdinhngo/code-atlas"
# A user-scope plugin fires in every project: the shell test spares a repo with no index the
# Python spawn, so each hook is silent there (344 Scope 3).
PLUGIN_GATE = '[ -d "${CLAUDE_PROJECT_DIR:-.}/.code-atlas" ] || exit 0; exec '

# An adapter announces its suffixes in its entry file; the handshake sends this same literal.
# Reading it statically is what lets a guard check coverage without starting a subprocess.
_EXT_DECL = re.compile(r"""extensions['"]?\s*(?::|=>)\s*[\[(]([^\])]*)[\])]""")
_EXT_ITEM = re.compile(r"""['"](\.[A-Za-z0-9_]+)['"]""")


class _PromptRecorder:
    """Stands in for the FastMCP server so `prompts.register` can be read, not imported.

    `which_tool` is a closure inside `register`, and `register` only ever calls
    `server.prompt(name=…)(fn)` — so one method is the whole surface it needs.
    """

    def __init__(self) -> None:
        self.prompts: dict[str, Callable[..., str]] = {}

    def prompt(self, name: str) -> Callable[[Callable[..., str]], Callable[..., str]]:
        def keep(fn: Callable[..., str]) -> Callable[..., str]:
            self.prompts[name] = fn
            return fn

        return keep


def recognition_map() -> list[str]:
    """The `which_tool` map, as its `- question -> tool.` lines, in the order the prompt emits."""
    recorder = _PromptRecorder()
    prompts.register(recorder)  # type: ignore[arg-type]
    body = recorder.prompts[prompts.WHICH_TOOL]()
    return [line for line in body.splitlines() if line.startswith("- ")]


def declared_extensions(adapters_dir: Path | None = None) -> dict[str, tuple[str, ...]]:
    """Each shipped adapter's declared suffixes, read from its own entry file.

    An adapter whose declaration does not parse maps to `()` — so it reads as uncovered and turns
    the coverage guard red, rather than passing quietly.
    """
    root = ADAPTERS_DIR if adapters_dir is None else adapters_dir
    found: dict[str, tuple[str, ...]] = {}
    for name in shipped_adapters(root):
        found[name] = ()
        for path in sorted(p for p in (root / name).iterdir() if p.is_file()):
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            match = _EXT_DECL.search(text)
            if match:
                found[name] = tuple(_EXT_ITEM.findall(match.group(1)))
                break
    return found


def render_skill() -> str:
    """`SKILL.md` — the map plus the roster, and nothing that could disagree with the server."""
    lines = [
        "---",
        "name: code-atlas",
        "description: >-",
        "  Route a question about an unfamiliar codebase to the right code-atlas MCP tool —",
        "  search, read, callers, references, impact, architecture, onboarding. Use when the",
        "  code-atlas server is connected and you are deciding which of its tools answers the",
        "  question in front of you.",
        "---",
        "",
        "# code-atlas — which tool answers which question",
        "",
        f"Generated by `scripts/gen_skill.py` from the {len(TOOL_NAMES)} tools the server",
        "registers and from the `which_tool` recognition map. Do not edit by hand: a drift guard",
        "compares this file to its source, so a hand edit is a red test, not a quiet",
        "disagreement.",
        "",
        "## Recognition map",
        "",
    ]
    lines.extend(recognition_map())
    lines.extend(
        [
            "",
            "Call `get_index_status` first whenever you are unsure the index is current.",
            "",
            "## The served surface",
            "",
        ]
    )
    lines.extend(f"{n}. `{name}`" for n, name in enumerate(TOOL_NAMES, start=1))
    lines.extend(
        [
            "",
            "## What this skill is not",
            "",
            "It carries the map, never a second set of tool descriptions — the descriptions the",
            "client shows you are the ones that route, and a copy here could disagree with them.",
            "It holds no live state either: index freshness, symbol counts and open work are what",
            "the tools are for, and a number frozen into this file would be a wrong answer rather",
            "than a stale one.",
            "",
        ]
    )
    return "\n".join(lines)


def _suffix_filter(*tools: str) -> str:
    """A hook `if` filter over every shipped adapter's declared suffixes, for the named tools."""
    suffixes = [suffix for _, group in sorted(declared_extensions().items()) for suffix in group]
    return "|".join(f"{tool}(*{s})" for s in suffixes for tool in tools)


def render_claude_code_snippet() -> str:
    """Every Claude Code hook code-atlas offers: the edit poke (036), the signal (099) and the
    session-boundary state line (322) — `SessionStart` covers the post-compaction delivery.

    099 shipped the signal wired for Codex only; 240 is the guard-less drift that let that stand.
    `Read` belongs at PostToolUse (the line rides the result); `Write` at PreToolUse, because the
    create-vs-edit test is whether the path exists yet — see `docs/TOOLS.md`.
    """
    return json.dumps({"hooks": _claude_code_hooks(lambda name: name)}, indent=2) + "\n"


def _claude_code_hooks(command: Callable[[str], str]) -> dict[str, Any]:
    """The one hook table: the snippet names each console script, the plugin gates it (344)."""
    return {
        "PostToolUse": [
            {
                "matcher": "Edit|Write",
                "hooks": [
                    {
                        "type": "command",
                        "command": command("code-atlas-poke"),
                        "if": _suffix_filter("Edit", "Write"),
                        "async": True,
                        "timeout": 60,
                    }
                ],
            },
            {
                "matcher": "Read",
                "hooks": [
                    {
                        "type": "command",
                        "command": command("code-atlas-signal"),
                        "if": _suffix_filter("Read"),
                        "timeout": 10,
                    }
                ],
            },
        ],
        "PreToolUse": [
            {
                "matcher": "Write",
                "hooks": [
                    {
                        "type": "command",
                        "command": command("code-atlas-signal"),
                        "if": _suffix_filter("Write"),
                        "timeout": 10,
                    }
                ],
            }
        ],
        "SessionStart": [
            {"hooks": [{"type": "command", "command": command("code-atlas-state"), "timeout": 10}]}
        ],
        "PreCompact": [
            {"hooks": [{"type": "command", "command": command("code-atlas-state"), "timeout": 10}]}
        ],
    }




def render_plugin_hooks() -> str:
    """The snippet's hooks, each gated on the index, plus a background refresh at start (344)."""
    hooks = _claude_code_hooks(lambda name: PLUGIN_GATE + name)
    refresh = {"type": "command", "command": PLUGIN_GATE + "code-atlas-refresh"}
    hooks["SessionStart"].append({"hooks": [{**refresh, "async": True, "timeout": 600}]})
    return json.dumps({"hooks": hooks}, indent=2) + "\n"


def _package() -> dict[str, Any]:
    project: dict[str, Any] = tomllib.loads((REPO / "pyproject.toml").read_text(encoding="utf-8"))
    return dict(project["project"])


def render_plugin_manifest() -> str:
    """Name, version and description from the package, so the plugin never lags it (R6.7)."""
    package = _package()
    manifest = {
        "name": package["name"],
        "version": package["version"],
        "description": package["description"],
        "author": {"name": "cuongdinhngo"},
        "homepage": REPOSITORY_URL,
        "repository": REPOSITORY_URL,
        "license": package["license"]["text"],
    }
    return json.dumps(manifest, indent=2) + "\n"


def render_plugin_mcp() -> str:
    """The server by its console-script name; Claude Code starts it in the project dir (344)."""
    return json.dumps({"mcpServers": {"code-atlas": {"command": "code-atlas"}}}, indent=2) + "\n"


def render_marketplace() -> str:
    """This repo as a one-plugin marketplace: `/plugin marketplace add cuongdinhngo/code-atlas`."""
    package = _package()
    plugin = {
        "name": package["name"],
        "source": "./" + PLUGIN_DIR.relative_to(REPO).as_posix(),
        "description": package["description"],
        "version": package["version"],
    }
    market = {
        "name": package["name"],
        "owner": {"name": "cuongdinhngo"},
        "metadata": {"description": "code-atlas as a Claude Code plugin: server, hooks and skill."},
        "plugins": [plugin],
    }
    return json.dumps(market, indent=2) + "\n"


GENERATED: dict[Path, Callable[[], str]] = {
    SKILL_PATH: render_skill,
    CLAUDE_CODE_SNIPPET_PATH: render_claude_code_snippet,
    PLUGIN_MANIFEST_PATH: render_plugin_manifest,
    PLUGIN_MCP_PATH: render_plugin_mcp,
    PLUGIN_HOOKS_PATH: render_plugin_hooks,
    PLUGIN_SKILL_PATH: render_skill,
    MARKETPLACE_PATH: render_marketplace,
}

# Occasions that earn their keep in the field (266 + 300) — tools must appear in which_tool.
# Titles are the occasions; tool names select lines from recognition_map() (R6.7).
OCCASIONS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Before renaming a symbol", ("find_references", "find_callers", "impact")),
    ("After editing indexed code", ("get_index_status", "find_callers", "impact")),
    ("First session on this repo", ("get_index_status", "architecture_overview", "guided_tour")),
    (
        "A name that exists in two languages",
        ("search_symbol", "get_index_status"),
    ),
    ("Writing the PR claim", ("find_callers", "impact", "get_index_status")),
    (
        "Explaining how a request moves through the system",
        ("get_index_status", "trace_capability", "architecture_overview"),
    ),
)

BRIEF_BEGIN = "<!-- code-atlas:agent-brief -->"
BRIEF_END = "<!-- /code-atlas:agent-brief -->"
BRIEF_HEADING = "## code-atlas — when to ask the graph"
# Claude Code's project-memory list is CLAUDE.md / CLAUDE.local.md only (270) — never write those.
AGENTS_IMPORT_LINE = "@AGENTS.md"
CLAUDE_MEMORY_FILES = ("CLAUDE.md", "CLAUDE.local.md")
CLAUDE_IMPORT_OFFER = (
    "Claude Code loads CLAUDE.md / CLAUDE.local.md only — add this one line to CLAUDE.md "
    f"(or CLAUDE.local.md): {AGENTS_IMPORT_LINE}"
)


def recognition_lines_by_tool() -> dict[str, str]:
    """First ``which_tool`` line naming each tool — the one parse of that map (R6.7)."""
    lines_by_tool: dict[str, str] = {}
    for line in recognition_map():
        # "- question -> tool." or "- question -> tool (note)."
        if "->" not in line:
            continue
        rhs = line.split("->", 1)[1].strip()
        lines_by_tool.setdefault(rhs.split()[0].rstrip("."), line)
    return lines_by_tool


# Usage rules, not a second copy of the recognition map (R6.7): the map says WHICH tool, these say
# how to spend the calls. Each line is charged to every session in the consuming repo — 300's H4
# (one index call, then 29 greps) and the field retros are what earn them a place.
USAGE_RULES: tuple[str, ...] = (
    "### How to spend the calls",
    "",
    "- **Ask the index first, then follow through.** Structural questions take more than one"
    " call: `search_symbol` → `read_symbol`, `find_callers` → `impact`. One lookup followed by"
    " a grep sweep is the failure mode this brief exists to stop.",
    "- **Call `get_index_status` when you are unsure the index is current** — and read"
    " `staleness`. A `behind` index still serves `search_symbol` and `read_symbol`; the inbound"
    " tools need `serve_behind: true` and then label the answer.",
    "- **Prefer one call over a sweep of ten.** `search_symbol` takes a list of `queries`.",
    "",
    "### Read what the answer says about itself",
    "",
    "- `total_count` is the population, `truncated` describes the page alone — page 1 of"
    " `find_callers` is tier-ordered (RESOLVED first), not a ranking of importance.",
    "- `production_count` / `test_count` split inbound answers by the caller's role."
    " *Three callers* and *three callers, all in one test* are different answers;"
    " `exclude_tests=true` filters before paging on `find_callers` (any depth — test nodes"
    " are pruned from the walk) and on `search_symbol` / `impact`, so page 1 is production.",
    "- `confidence_tier` is per edge: `RESOLVED` is a linked definition, `HEURISTIC` and"
    " `DYNAMIC` are candidates. Never quote a candidate as a fact.",
    "- **`unconfigured_adapters`, `unindexed_languages` and `unindexed_same_basename` mean the"
    " index never looked** — not that nothing is there. They are omitted when empty, so seeing"
    " one is the signal, and `detail_level: \"minimal\"` hides all three.",
    "",
    "### What it cannot answer — use grep instead",
    "",
    "The index holds what the adapters parsed, so a question whose answer is an **absence**"
    " cannot be settled here: *is there a call site that forgets the check*, *does anything still"
    " use the old constant*, *which of these has no test*. Ask the positive form"
    " (`find_callers`, `find_references`), then subtract — and keep grep for literal text in"
    " strings, comments and config.",
    "",
    "### Two traps that cost real time",
    "",
    "- **A name defined in more than one tree** (`src/` beside a `legacy/` copy) makes `impact`"
    " and `read_symbol` answer `reason: subject_ambiguous` with no rows — and the payload"
    " carries `ambiguous_definitions`. Re-ask `read_symbol` with `path_prefix` naming one"
    " site from that list (327); do not read the empty result as no impact.",
    "- **Mirrored trees inflate a result set.** A hit carries `mirror_counterpart` when an"
    " indexed twin exists; read it before concluding a symbol has many call sites.",
    "",
    "### Filters, writers, and what the index will not name (313)",
    "",
    "- **Narrow a large `search_symbol` page with `kind:` or `namespace`.** A common token"
    " across File/Class/Method rows is not a reason to eyeball hundreds of hits — pass"
    " `kind` (a contract node kind) or `namespace` and re-ask.",
    "- **Scope a `search_symbol` / `find_references` / `read_symbol` page to a subtree with"
    " `path_prefix`.** An index-root-relative plain prefix (`src/`); a hit outside it answers"
    " `path_excluded` (search/refs) or `no_such_symbol` naming the filter (read) — not a silent"
    " wrong body (315/327).",
    "- **`find_references` on a Table or Column returns its writers** — linked `WRITES`, plus"
    " `DELETES` on the Table (278/328). Prefer that over asking who calls a nearby method"
    " when the question is *what writes this column*.",
    "- **A dynamic-SQL / `EXEC`-created object is not a symbol.** Grep the SQL text; the"
    " index reads as absence. `find_orphans` then says `status=resolution_unmodelled` when"
    " a language stamped `dynamic_sql` (296).",
    "- **A runtime-loaded module is not an edge either.** A non-literal `import()` / `require()`"
    " / `importlib` stamps `dynamic_import`, a registered class autoloader stamps `autoload`:"
    " the target is never linked, so a missing importer is not proof of none — Grep the loader"
    " call. `find_orphans` answers `status=resolution_unmodelled` for either (279/294/295).",
    "- **`find_orphans` has no path scope** — it walks the whole index from"
    " `CA_ENTRY_POINTS`. Do not expect a directory filter.",
    "",
    "Hook snippets (edit poke / write-time signal) stay **offered** under",
    "`contrib/claude-code/` — the server never writes editor settings (036/099).",
    "",
)

def render_agent_brief() -> str:
    """Agent brief selected from the live ``which_tool`` map (tasks 266 / 300)."""
    lines_by_tool = recognition_lines_by_tool()
    missing = [
        tool
        for _title, tools in OCCASIONS
        for tool in tools
        if tool not in lines_by_tool
    ]
    if missing:
        raise RuntimeError(f"which_tool map missing tools named by OCCASIONS: {missing}")
    out = [
        BRIEF_HEADING,
        "",
        "Generated by `scripts/gen_skill.py` from the `which_tool` recognition map.",
        "Do not edit by hand — regenerate with",
        "`python scripts/gen_skill.py --write-agent-brief <repo>`.",
        "",
    ]
    for title, tools in OCCASIONS:
        out.append(f"### {title}")
        out.append("")
        for tool in tools:
            out.append(lines_by_tool[tool])
        out.append("")
    out.extend(USAGE_RULES)
    return "\n".join(out)


GENERATED[AGENT_BRIEF_PATH] = render_agent_brief


def claude_md_lacks_agents_import(repo_root: Path) -> bool:
    """True when CLAUDE.md exists and neither memory file already imports AGENTS.md (270)."""
    root = repo_root.resolve()
    if not (root / "CLAUDE.md").is_file():
        return False
    # The offer names either file, so either one satisfying it must silence the offer.
    return not any(
        (root / name).is_file()
        and AGENTS_IMPORT_LINE in (root / name).read_text(encoding="utf-8")
        for name in CLAUDE_MEMORY_FILES
    )


def write_agent_brief(repo_root: Path) -> Path:
    """Install the brief into repo_root/AGENTS.md idempotently (266); offer Claude import (270)."""
    root = repo_root.resolve()
    path = root / "AGENTS.md"
    body = render_agent_brief().rstrip() + "\n"
    block = f"{BRIEF_BEGIN}\n{body}{BRIEF_END}\n"
    if path.is_file():
        text = path.read_text(encoding="utf-8")
        if BRIEF_BEGIN in text and BRIEF_END in text:
            before, rest = text.split(BRIEF_BEGIN, 1)
            _old, after = rest.split(BRIEF_END, 1)
            text = before + block + after.lstrip("\n")
        else:
            sep = "" if text.endswith("\n") or not text else "\n"
            text = text + sep + "\n" + block
    else:
        text = block
    path.write_text(text, encoding="utf-8")
    # Print, never write CLAUDE.md (PLAN §19 / 270).
    if claude_md_lacks_agents_import(root):
        print(CLAUDE_IMPORT_OFFER)
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="rewrite the generated files in place")
    parser.add_argument(
        "--write-agent-brief",
        metavar="REPO",
        help="write/replace the AGENTS.md brief section in REPO (task 266)",
    )
    args = parser.parse_args(argv)
    if args.write_agent_brief:
        dest = write_agent_brief(Path(args.write_agent_brief))
        print(f"wrote {dest}")
        return 0
    stale = []
    for path, render in GENERATED.items():
        wanted = render()
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(wanted, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO)}")
        elif not path.is_file() or path.read_text(encoding="utf-8") != wanted:
            stale.append(path.relative_to(REPO).as_posix())
    for name in stale:
        print(f"stale: {name} — run `python scripts/gen_skill.py --write`", file=sys.stderr)
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
